replicaCount: 1

image:
  repository: techiescamp/pomodoro-frontend
  tag: "4.0.0"
  pullPolicy: IfNotPresent

configmap:
  mountpath: /app/.env
  subpath: .env

service:
  type: NodePort
  port: 3000
  nodeport: 32749

## Configmap template file data
backend_url: http://pomodoro-backend.be-pomodoro.svc.cluster.local:7000
api_url: /api