apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: {{ .Values.backend_url }}
            - name: REACT_APP_UI_URL
              value: {{ .Values.api_url }}
          ports:
            - containerPort: {{ .Values.service.port }}
